import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const navItems = [
    {
      name: "Home",
      url: "/",
    },
    {
      name: "Services",
      url: "/services",
    },
    {
      name: "Features",
      url: "/features",
    },
    {
      name: "Product",
      url: "/product",
    },
    {
      name: "Testimonial",
      url: "/testimonial",
    },
    {
      name: "FAQ",
      url: "/faq",
    },
  ];

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <div className="header-inner">
            <Link href="/" className="logo">
              <img src="/img/logo.png" alt="logo" />
            </Link>

            <nav>
              {navItems.map((item) => (
                <Link href={item.url} key={item.name}>
                  {item.name}
                </Link>
              ))}
            </nav>

            <div className="action-group">
              <button className="login">Login</button>

              <button className="signup">Sign up</button>
            </div>
          </div>
        </header>

        <main>{children}</main>

        {/* FOOTER */}
        <footer className="footer">
          <div className="footer-container">
            <div className="footer-left">
              <img src="/img/nex.png" alt="footer logo" />

              <p>
                Copyright © 2020 Nexcent ltd.
                <br />
                All rights reserved
              </p>

              <div className="icon-mxh">
                <img src="/img/footer_logo1.png" alt="instagram" />
                <img src="/img/footer_logo2.png" alt="dribbble" />
                <img src="/img/footer_logo3.png" alt="twitter" />
                <img src="/img/footer_logo4.png" alt="youtube" />
              </div>
            </div>

            <div className="footer-col">
              <h3>Company</h3>

              <ul>
                <li>
                  <Link href="/about">About us</Link>
                </li>

                <li>
                  <Link href="/blog">Blog</Link>
                </li>

                <li>
                  <Link href="/contact">Contact us</Link>
                </li>

                <li>
                  <Link href="/pricing">Pricing</Link>
                </li>
              </ul>
            </div>

            <div className="footer-col">
              <h3>Support</h3>

              <ul>
                <li>
                  <Link href="/help">Help center</Link>
                </li>

                <li>
                  <Link href="/terms">Terms of service</Link>
                </li>

                <li>
                  <Link href="/legal">Legal</Link>
                </li>

                <li>
                  <Link href="/privacy">Privacy policy</Link>
                </li>
              </ul>
            </div>

            <div className="footer-col">
              <h3>Stay up to date</h3>

              <div className="email-box">
                <input type="text" placeholder="Your email address" />
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
